apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fmh1jkr8b-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:64ac9ffb7a1d9e69c3c3d99b26169edf421e82be@sha256:920dee8b68b5f806c4d4f56a9001da9353082f66f64a62c3a80b68f9b2a5cd7e
          name: container-image
